export const REMOTE_PLAY = 'REMOTE_PLAY'

export const ADD_TRACKS = 'ADD_TRACKS'
export const ADD_TRACKS_ERROR = 'ADD_TRACKS_ERROR'

export const CURRENT_TRACK = 'CURRENT_TRACK'
export const PLAYER_STATE = 'PLAYER_STATE'
export const SET_PERMISSIONS = 'SET_PERMISSIONS'
export const SET_PERMISSIONS_ERROR = 'SET_PERMISSIONS'